#!/bin/bash
# Run the Navigator app with typical args for test/dev

[[ -z $1 ]] && profile="dev" || profile=$1

# How to run the uberjar:
# java -cp target/navigator-0.1.0-SNAPSHOT-standalone.jar clojure.main -m navigator.core

mydir=~/.navigator/
shift
case $profile in
    dev) lein run --config-path $mydir $*
        ;;
    prod) echo 'Not yet! Are you crazy?'
        ;;
    *) echo 'run saith: I did not understand what you wanted me to do.';
        ;;
esac
