#!/bin/bash
# Run the Aspire app with typical args for test/dev

[[ -z $1 ]] && profile="dev" || profile=$1

shift
case $profile in
    dev) lein run --conf-sql-db ~/.aspire/conf-sql-db.edn $*
        ;;
    prod) echo 'Not yet! Are you crazy?'
        ;;
    *) echo 'run saith: I did not understand what you wanted me to do.';
        ;;
esac
