insert into comp (name, version) values ('Can add vectors', 'v1');
insert into comp (name, version) values ('Can draw circles', 'v1');
insert into comp (name, version) values ('Can say "hegemon" in Spanish', 'v1');
insert into comp (name, version) values ('Can say "disjunctivist" in English', 'v1');
insert into comp (name, version) values ('Can write restaurant criticism', 'v1');
insert into comp (name, version) values ('Can create balloon animals', 'v1');
insert into comp (name, version) values ('Can compose trios for washboard', 'v1');
insert into comp_tag (name, version, type, disp_level_num) values ('VLACS HS Diploma', 'v1', 'program-of-study', 0);
insert into comp_tag (name, version, type, disp_level_num) values ('Mathematics', 'v1', 'area-of-study', 1);
insert into comp_tag (name, version, type, disp_level_num) values ('English', 'v1', 'area-of-study', 1);
insert into comp_tag (name, version, type, disp_level_num) values ('Foreign Language', 'v1', 'area-of-study', 1);
insert into comp_tag (name, version, type, disp_level_num) values ('Quantitative Skills', 'v1', 'cluster', 1);
insert into comp_tag (name, version, type, disp_level_num) values ('Critical and Creative Thinking', 'v1', 'cluster', 1);
insert into comp_tag (name, version, type, disp_level_num) values ('Geometry', 'v1', 'course', 2);
insert into comp_tag (name, version, type, disp_level_num) values ('English 1', 'v1', 'course', 2);
insert into comp_tag (name, version, type, disp_level_num) values ('Spanish 1', 'v1', 'course', 2);
insert into comp_tag (name, version, type, disp_level_num) values ('Music Theory', 'v1', 'course', 2);
insert into comp_tag (name, version, type, disp_level_num) values ('Musical Intelligence', 'v1', 'cluster', 1);
insert into comp2comp_tag (comp_id, comp_tag_id) values (1, 1);
insert into comp2comp_tag (comp_id, comp_tag_id) values (1, 2);
insert into comp2comp_tag (comp_id, comp_tag_id) values (1, 5);
insert into comp2comp_tag (comp_id, comp_tag_id) values (1, 7);
insert into comp2comp_tag (comp_id, comp_tag_id) values (2, 1);
insert into comp2comp_tag (comp_id, comp_tag_id) values (2, 2);
insert into comp2comp_tag (comp_id, comp_tag_id) values (2, 5);
insert into comp2comp_tag (comp_id, comp_tag_id) values (2, 7);
insert into comp2comp_tag (comp_id, comp_tag_id) values (3, 1);
insert into comp2comp_tag (comp_id, comp_tag_id) values (3, 4);
insert into comp2comp_tag (comp_id, comp_tag_id) values (3, 9);
insert into comp2comp_tag (comp_id, comp_tag_id) values (4, 1);
insert into comp2comp_tag (comp_id, comp_tag_id) values (4, 3);
insert into comp2comp_tag (comp_id, comp_tag_id) values (4, 8);
insert into comp2comp_tag (comp_id, comp_tag_id) values (5, 6);
insert into comp2comp_tag (comp_id, comp_tag_id) values (5, 8);
insert into comp2comp_tag (comp_id, comp_tag_id) values (7, 10);
insert into comp2comp_tag (comp_id, comp_tag_id) values (7, 11);
