insert into comp (name, version, status) values ('Can add vectors', 'v1', 'active');
insert into comp (name, version, status) values ('Can draw circles', 'v1', 'active');
insert into comp (name, version, status) values ('Can say "hegemon" in Spanish', 'v1', 'active');
insert into comp (name, version, status) values ('Can say "disjunctivist" in English', 'v1', 'active');
insert into comp (name, version, status) values ('Can write restaurant criticism', 'v1', 'active');
insert into comp (name, version, status) values ('Can create balloon animals', 'v1', 'active');
insert into comp (name, version, status) values ('Can compose trios for washboard', 'v1', 'active');

insert into comp_tag (name, version, type, status) values ('VLACS HS Diploma', 'v1', 'program-of-study', 'active');
insert into comp_tag (name, version, type, status) values ('Mathematics', 'v1', 'area-of-study', 'active');
insert into comp_tag (name, version, type, status) values ('English', 'v1', 'area-of-study', 'active');
insert into comp_tag (name, version, type, status) values ('Foreign Language', 'v1', 'area-of-study', 'active');
insert into comp_tag (name, version, type, status) values ('Geometry', 'v1', 'course', 'active');
insert into comp_tag (name, version, type, status) values ('English 1', 'v1', 'course', 'active');
insert into comp_tag (name, version, type, status) values ('Spanish 1', 'v1', 'course', 'active');
insert into comp_tag (name, version, type, status) values ('Music Theory', 'v1', 'course', 'active');
insert into comp_tag (name, version, type, status) values ('Quantitative Skills', 'v1', 'cluster', 'active');
insert into comp_tag (name, version, type, status) values ('Critical and Creative Thinking', 'v1', 'cluster', 'active');
insert into comp_tag (name, version, type, status) values ('Musical Intelligence', 'v1', 'cluster', 'active');

insert into comp2comp_tag (comp_id, comp_tag_id) values ((select id from comp where name = 'Can add vectors'), (select id from comp_tag where name = 'VLACS HS Diploma'));
insert into comp2comp_tag (comp_id, comp_tag_id) values ((select id from comp where name = 'Can add vectors'), (select id from comp_tag where name = 'Mathematics'));
insert into comp2comp_tag (comp_id, comp_tag_id) values ((select id from comp where name = 'Can add vectors'), (select id from comp_tag where name = 'Quantitative Skills'));
insert into comp2comp_tag (comp_id, comp_tag_id) values ((select id from comp where name = 'Can add vectors'), (select id from comp_tag where name = 'Geometry'));
insert into comp2comp_tag (comp_id, comp_tag_id) values ((select id from comp where name = 'Can draw circles'), (select id from comp_tag where name = 'VLACS HS Diploma'));
insert into comp2comp_tag (comp_id, comp_tag_id) values ((select id from comp where name = 'Can draw circles'), (select id from comp_tag where name = 'Mathematics'));
insert into comp2comp_tag (comp_id, comp_tag_id) values ((select id from comp where name = 'Can draw circles'), (select id from comp_tag where name = 'Quantitative Skills'));
insert into comp2comp_tag (comp_id, comp_tag_id) values ((select id from comp where name = 'Can draw circles'), (select id from comp_tag where name = 'Geometry'));
insert into comp2comp_tag (comp_id, comp_tag_id) values ((select id from comp where name = 'Can say "hegemon" in Spanish'), (select id from comp_tag where name = 'VLACS HS Diploma'));
insert into comp2comp_tag (comp_id, comp_tag_id) values ((select id from comp where name = 'Can say "hegemon" in Spanish'), (select id from comp_tag where name = 'Foreign Language'));
insert into comp2comp_tag (comp_id, comp_tag_id) values ((select id from comp where name = 'Can say "hegemon" in Spanish'), (select id from comp_tag where name = 'Spanish 1'));
insert into comp2comp_tag (comp_id, comp_tag_id) values ((select id from comp where name = 'Can say "disjunctivist" in English'), (select id from comp_tag where name = 'VLACS HS Diploma'));
insert into comp2comp_tag (comp_id, comp_tag_id) values ((select id from comp where name = 'Can say "disjunctivist" in English'), (select id from comp_tag where name = 'English'));
insert into comp2comp_tag (comp_id, comp_tag_id) values ((select id from comp where name = 'Can say "disjunctivist" in English'), (select id from comp_tag where name = 'English 1'));
insert into comp2comp_tag (comp_id, comp_tag_id) values ((select id from comp where name = 'Can write restaurant criticism'), (select id from comp_tag where name = 'Critical and Creative Thinking'));
insert into comp2comp_tag (comp_id, comp_tag_id) values ((select id from comp where name = 'Can write restaurant criticism'), (select id from comp_tag where name = 'English 1'));
insert into comp2comp_tag (comp_id, comp_tag_id) values ((select id from comp where name = 'Can create balloon animals'), (select id from comp_tag where name = 'Music Theory'));
insert into comp2comp_tag (comp_id, comp_tag_id) values ((select id from comp where name = 'Can create balloon animals'), (select id from comp_tag where name = 'VLACS HS Diploma'));

insert into comp_tag2parent (child_comp_tag_id, parent_comp_tag_id) values ((select id from comp_tag where name = 'Geometry'), (select id from comp_tag where name = 'Quantitative Skills'));
insert into comp_tag2parent (child_comp_tag_id, parent_comp_tag_id) values ((select id from comp_tag where name = 'Geometry'), (select id from comp_tag where name = 'Mathematics'));
insert into comp_tag2parent (child_comp_tag_id, parent_comp_tag_id) values ((select id from comp_tag where name = 'Geometry'), (select id from comp_tag where name = 'VLACS HS Diploma'));
insert into comp_tag2parent (child_comp_tag_id, parent_comp_tag_id) values ((select id from comp_tag where name = 'English 1'), (select id from comp_tag where name = 'English'));
insert into comp_tag2parent (child_comp_tag_id, parent_comp_tag_id) values ((select id from comp_tag where name = 'English 1'), (select id from comp_tag where name = 'Critical and Creative Thinking'));
insert into comp_tag2parent (child_comp_tag_id, parent_comp_tag_id) values ((select id from comp_tag where name = 'English 1'), (select id from comp_tag where name = 'VLACS HS Diploma'));
insert into comp_tag2parent (child_comp_tag_id, parent_comp_tag_id) values ((select id from comp_tag where name = 'Spanish 1'), (select id from comp_tag where name = 'Foreign Language'));
insert into comp_tag2parent (child_comp_tag_id, parent_comp_tag_id) values ((select id from comp_tag where name = 'Music Theory'), (select id from comp_tag where name = 'Critical and Creative Thinking'));
insert into comp_tag2parent (child_comp_tag_id, parent_comp_tag_id) values ((select id from comp_tag where name = 'Music Theory'), (select id from comp_tag where name = 'Musical Intelligence'));
